import type { Market } from "./types";

export const markets: Market[] = [
  {
    aiReview: {
      evidence: [
        {
          domain: "coinmarketcap.com",
          kind: "provided_url",
          sourceTier: "specialist",
          summary:
            "Live ETH/USD price feed aggregated across major spot exchanges; suitable for verifying a $5,000 print.",
          title: "Ethereum price | CoinMarketCap",
          url: "https://coinmarketcap.com/currencies/ethereum/",
        },
        {
          domain: "reuters.com",
          kind: "search_result",
          sourceTier: "major_news",
          summary:
            "Coverage of prior ETH all-time-high runs confirms major outlets report threshold crossings promptly.",
          title: "Ether hits record high",
          url: "https://www.reuters.com/markets/currencies/",
        },
      ],
      hardFlags: [],
      modelId: "claude-sonnet-4-5",
      provider: "anthropic",
      reasons: [
        "Question has a bright-line numeric threshold and a fixed UTC deadline.",
        "Outcome is publicly verifiable from multiple independent price feeds.",
        "Minor ambiguity about which exchanges count as 'major' adds slight dispute risk.",
      ],
      reviewedAt: "2026-06-02T09:15:00.000Z",
      scores: {
        contentSafety: 5,
        corroboration: 5,
        disputeRisk: 2,
        objectivity: 4,
        promptInjectionRisk: 0,
        publicKnowability: 5,
        sourceQuality: 4,
      },
      sourceChecks: [
        {
          domain: "coinmarketcap.com",
          notes: "Aggregated price index reachable and relevant to the threshold.",
          relevant: true,
          sourceTier: "specialist",
          url: "https://coinmarketcap.com/currencies/ethereum/",
        },
      ],
      verdict: "approve",
    },
    b: 5_000,
    category: "Crypto",
    closesAt: "2026-08-01T00:00:00.000Z",
    createdAt: "2026-06-01T14:30:00.000Z",
    creator: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    description:
      "Resolves YES if a major spot exchange prints ETH at or above $5,000 before August 1, 2026 UTC.",
    graduationTargetUsd: 482_000,
    id: "eth-5000-august",
    matchedUsd: 356_000,
    metadataHash: "0x7a1c2b3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef",
    noPriceCents: 36,
    openingProbability: 50,
    pricePath: [28, 31, 35, 39, 44, 47, 53, 57, 61, 64],
    question: "Will ETH flip $5,000 before August?",
    receiptCount: 1_284,
    resolutionCriteria:
      "Resolves YES if ETH/USD trades at or above $5,000.00 on Coinbase, Binance, or Kraken spot markets at any moment before 2026-08-01 00:00 UTC. Resolves NO otherwise. Wicks count; derivatives prices do not.",
    resolutionSources: [
      "https://coinmarketcap.com/currencies/ethereum/",
      "https://www.coinbase.com/price/ethereum",
    ],
    resolutionUrl: "https://coinmarketcap.com/currencies/ethereum/",
    status: "graduating",
    volumeUsd: 482_300,
    yesPriceCents: 64,
  },
  {
    b: 3_000,
    category: "Politics",
    closesAt: "2026-07-29T18:00:00.000Z",
    description:
      "Resolves YES if the target range decreases at the next scheduled FOMC decision.",
    graduationTargetUsd: 150_000,
    id: "fed-cut-next-meeting",
    matchedUsd: 38_000,
    noPriceCents: 59,
    openingProbability: 45,
    pricePath: [49, 46, 44, 43, 41, 42, 40, 41],
    question: "Will the Fed cut rates at the next meeting?",
    receiptCount: 412,
    status: "bootstrap",
    volumeUsd: 96_700,
    yesPriceCents: 41,
  },
  {
    b: 2_500,
    category: "Sports",
    closesAt: "2026-09-01T00:00:00.000Z",
    description:
      "Resolves YES if the pre-match betting underdog wins the next designated major final.",
    graduationTargetUsd: 120_000,
    id: "underdog-major-final",
    matchedUsd: 12_500,
    noPriceCents: 78,
    openingProbability: 20,
    outcomeNo: "Favorite",
    outcomeYes: "Underdog",
    pricePath: [18, 19, 21, 20, 22, 23, 22],
    question: "Will an underdog win the next major final?",
    receiptCount: 207,
    status: "bootstrap",
    volumeUsd: 54_100,
    yesPriceCents: 22,
  },
  {
    b: 5_000,
    category: "Tech",
    closesAt: "2026-06-30T23:59:59.000Z",
    description:
      "Resolves YES if an identified frontier lab publicly releases a new generally available model before quarter end.",
    graduationTargetUsd: 300_000,
    id: "frontier-model-quarter",
    matchedUsd: 214_000,
    noPriceCents: 27,
    openingProbability: 60,
    pricePath: [55, 58, 60, 64, 66, 69, 73],
    question: "Will a frontier lab ship a new model this quarter?",
    receiptCount: 901,
    status: "graduating",
    volumeUsd: 318_900,
    yesPriceCents: 73,
  },
  {
    b: 8_000,
    category: "Crypto",
    closesAt: "2026-06-30T23:59:59.000Z",
    description:
      "Graduated market for whether BTC traded above its previous all-time high during Q2 2026.",
    graduationTargetUsd: 700_000,
    id: "btc-ath-q2",
    matchedUsd: 760_000,
    noPriceCents: 12,
    openingProbability: 70,
    pricePath: [71, 74, 78, 80, 82, 85, 88],
    question: "Did BTC set a new all-time high in Q2?",
    receiptCount: 3_120,
    status: "graduated",
    volumeUsd: 1_240_000,
    yesPriceCents: 88,
  },
  {
    b: 2_000,
    category: "Culture",
    closesAt: "2026-10-01T00:00:00.000Z",
    description:
      "Resolves YES if the nominated summer film reports at least $1B worldwide box office before its theatrical run closes.",
    graduationTargetUsd: 90_000,
    id: "summer-tentpole-billion",
    matchedUsd: 8_200,
    noPriceCents: 65,
    openingProbability: 30,
    pricePath: [29, 31, 34, 33, 35],
    question: "Will the summer tentpole cross $1B worldwide?",
    receiptCount: 158,
    status: "bootstrap",
    volumeUsd: 41_200,
    yesPriceCents: 35,
  },
];
