import type { HistoryRow } from "../coverage-report/coverageMetrics.ts";
import { renderCoverageSections } from "../coverage-report/coverageMetrics.ts";
import type { NightlyRun } from "../nightly-report/nightlyMetrics.ts";
import { renderNightlySection } from "../nightly-report/nightlyMetrics.ts";

/**
 * Renders the whole `TRENDS.md` view for the ci-metrics branch (ADR 0017): the
 * nightly lifecycle outcome first — the morning-glance signal — then the
 * per-workspace coverage tables.
 *
 * Both writers regenerate this file from the datastore: the coverage workflow
 * on every push to main, and the nightly workflow once a night. Each reads both
 * logs so its render carries the other's section intact — the file is a pure
 * view, never a place either writer owns half of. `nightlyRuns` defaults empty
 * so a coverage-only render (before the first nightly lands) is unchanged.
 *
 * The two sections stay separated (blank line + header) on purpose: when the
 * two workflows race a push to ci-metrics, each edits only its own section, so
 * git's 3-way merge on the loser's rebase auto-resolves (verified) and the
 * merged file carries both updates. Keep the sections apart; interleaving them
 * would turn that clean merge into a conflict. The nightly job additionally
 * rebuilds from the refetched datastore on retry, so it never depends on the
 * merge at all.
 */
export function renderTrends(
  coverageHistory: HistoryRow[],
  nightlyRuns: NightlyRun[] = [],
): string {
  const nightly = renderNightlySection(nightlyRuns);
  const coverage = renderCoverageSections(coverageHistory);
  const body = [nightly, coverage].filter((section) => section.length > 0);
  return [
    "# CI trends",
    "",
    "Generated by the test-observability and nightly-lifecycle workflows —",
    "do not edit by hand.",
    "",
    ...body,
  ].join("\n");
}
