// The mock collateral ABI comes straight from the protocol workspace package
// (protocol/src/generated/mock-collateral.ts, regenerated by `protocol build`).
// This re-export keeps ABIs quarantined under integrations/contracts: app code
// imports from here, never from @popcharts/protocol directly. The subpath
// export maps straight to the generated module; the package root re-exports
// with NodeNext `.js` specifiers that Turbopack does not rewrite to `.ts`
// inside node_modules.
export { mockCollateralAbi } from "@popcharts/protocol/mock-collateral";
