import { getAddress, isAddress, parseAbi } from "viem";

// The bounded-venue ABIs come from the protocol workspace package
// (protocol/src/generated/postgrad-venue.ts, regenerated by `protocol build`).
// Like pregrad-manager.ts, this re-export keeps ABIs quarantined under
// integrations/contracts: app code imports from here, never from
// @popcharts/protocol directly.
export { COMPLETE_SET_PRICE_POLICY } from "@popcharts/protocol/complete-set-price-policy";
// Re-exported, never reimplemented: the pool key is the pool's identity, and a
// local copy would diverge silently rather than fail.
export {
  buildOutcomePoolKey,
  type CompleteSetMarketPoolKey,
  computePoolId,
} from "@popcharts/protocol/outcome-pool-key";
export {
  boundedPoolOrderManagerAbi,
  completeSetBinaryMarketAbi,
  minimalV4SwapRouterAbi,
  poolTickBoundsAbi,
} from "@popcharts/protocol/postgrad-venue";
export { tickToSqrtPriceX96 } from "@popcharts/protocol/tick-to-sqrt-price";
// The vendored third-party venue contracts (v4 pool singleton, StateView
// lens, quoter) are compiled by the protocol build, so their ABIs come from
// the generated set too instead of hand-written fragments that drift.
export { poolManagerAbi, stateViewAbi } from "@popcharts/protocol/third-party/venue";

import { poolTickBoundsAbi } from "@popcharts/protocol/postgrad-venue";
import { v4QuoterAbi as vendoredV4QuoterAbi } from "@popcharts/protocol/third-party/venue";

/**
 * Quoter surface for the postgrad trade ticket. The quote functions are
 * nonpayable (they simulate a swap and revert internally), so callers run
 * them through `simulateContract`, never `writeContract`. The first-party
 * PoolTickBounds ABI is appended so the bounded hook's PoolTickOutOfBounds
 * revert — raised inside quote simulations — decodes into a readable error
 * instead of a raw selector.
 */
export const v4QuoterAbi = [...vendoredV4QuoterAbi, ...poolTickBoundsAbi] as const;

/**
 * The order manager's token puller settles maker deposits through an
 * allowance-transfer singleton (canonical Permit2 on public chains): it moves
 * tokens using the allowance the maker granted to the order manager, so a
 * limit order needs this grant in addition to the ERC20 approve on the puller.
 * Signature verified against Uniswap's Permit2 IAllowanceTransfer and the
 * protocol smoke flow (protocol/scripts/smoke-maker-order.ts). Local devchains
 * substitute a MockTokenPuller that pulls straight through the ERC20 allowance
 * and exposes neither function, so callers probe `allowance` and skip both.
 */
export const tokenPullerAllowanceAbi = parseAbi([
  "function allowance(address user, address token, address spender) view returns (uint160 amount, uint48 expiration, uint48 nonce)",
  "function approve(address token, address spender, uint160 amount, uint48 expiration)",
]);

/**
 * Venue contract addresses the postgrad trade ticket needs beyond the base
 * contract config: the swap router that executes fills, the tick-bounds
 * registry that anchors slippage limits, and (optionally) the v4 quoter for
 * exact quotes, the maker order manager for limit orders, and the StateView
 * lens for live pool ticks. All arrive as NEXT_PUBLIC env vars written by the
 * local deploy scripts (scripts/shared/env/postgradEnv.ts).
 */
export type PostgradVenueContractConfig = {
  orderManagerAddress: `0x${string}` | null;
  poolTickBoundsAddress: `0x${string}`;
  quoterAddress: `0x${string}` | null;
  stateViewAddress: `0x${string}` | null;
  swapRouterAddress: `0x${string}`;
};

/**
 * Reads the venue contract addresses from the environment. Returns null when
 * the swap router or tick bounds registry is missing — without those the
 * ticket cannot place a bounded swap, so callers fall back to the mock
 * environment. A missing quoter only downgrades quotes to pool-price
 * estimates; a missing order manager only disables limit orders, and a
 * missing StateView falls back to indexer-derived pool ticks.
 */
export function getPostgradVenueContractConfig(): PostgradVenueContractConfig | null {
  const swapRouterAddress = parseAddress(
    process.env.NEXT_PUBLIC_POPCHARTS_SWAP_ROUTER_ADDRESS
  );
  const poolTickBoundsAddress = parseAddress(
    process.env.NEXT_PUBLIC_POPCHARTS_POOL_TICK_BOUNDS_ADDRESS
  );

  if (!swapRouterAddress || !poolTickBoundsAddress) {
    return null;
  }

  return {
    orderManagerAddress: parseAddress(
      process.env.NEXT_PUBLIC_POPCHARTS_ORDER_MANAGER_ADDRESS
    ),
    poolTickBoundsAddress,
    quoterAddress: parseAddress(process.env.NEXT_PUBLIC_POPCHARTS_QUOTER_ADDRESS),
    stateViewAddress: parseAddress(
      process.env.NEXT_PUBLIC_POPCHARTS_STATE_VIEW_ADDRESS
    ),
    swapRouterAddress,
  };
}

function parseAddress(value: string | undefined): `0x${string}` | null {
  const address = value?.trim();

  if (!address || !isAddress(address)) {
    return null;
  }

  return getAddress(address);
}
