export const pregradManagerAbi = [
  {
    inputs: [
      { name: "cost", type: "uint256" },
      { name: "maxCost", type: "uint256" },
    ],
    name: "CostExceedsLimit",
    type: "error",
  },
  {
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "actual", type: "uint8" },
      { name: "expected", type: "uint8" },
    ],
    name: "InvalidMarketStatus",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidShares",
    type: "error",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "MarketDoesNotExist",
    type: "error",
  },
  {
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "graduationDeadline", type: "uint64" },
    ],
    name: "MarketPastGraduationDeadline",
    type: "error",
  },
  {
    inputs: [
      {
        components: [
          { name: "collateral", type: "address" },
          { name: "metadataHash", type: "bytes32" },
          { name: "metadataURI", type: "string" },
          { name: "openingProbabilityWad", type: "uint256" },
          { name: "liquidityParameter", type: "uint256" },
          { name: "graduationThreshold", type: "uint256" },
          { name: "graduationDeadline", type: "uint64" },
          { name: "resolutionTime", type: "uint64" },
          { name: "bypassAiResolution", type: "bool" },
        ],
        name: "params",
        type: "tuple",
      },
    ],
    name: "createMarket",
    outputs: [{ name: "marketId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { name: "marketId", type: "uint256" },
          { name: "side", type: "uint8" },
          { name: "shares", type: "uint256" },
          { name: "maxCost", type: "uint256" },
        ],
        name: "params",
        type: "tuple",
      },
    ],
    name: "placeReceipt",
    outputs: [{ name: "receiptId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "isTrustedCreator",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "creator", type: "address" }],
    name: "marketCreationFee",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "marketExists",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "side", type: "uint8" },
      { name: "shares", type: "uint256" },
    ],
    name: "quoteReceipt",
    outputs: [
      {
        components: [
          { name: "cost", type: "uint256" },
          { name: "rLow", type: "int256" },
          { name: "rHigh", type: "int256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { name: "marketId", type: "uint256" },
          { name: "receiptId", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "side", type: "uint8" },
          { name: "retainedShares", type: "uint256" },
          { name: "retainedCost", type: "uint256" },
          { name: "refund", type: "uint256" },
        ],
        name: "claim",
        type: "tuple",
      },
      { name: "proof", type: "bytes32[]" },
    ],
    name: "claimGraduatedReceipt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "receiptId", type: "uint256" }],
    name: "claimRefundedReceipt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "postgradAdapter", type: "address" },
    ],
    name: "finalizeGraduation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "getClearingRoot",
    outputs: [
      {
        components: [
          { name: "merkleRoot", type: "bytes32" },
          { name: "submitter", type: "address" },
          { name: "snapshotHash", type: "bytes32" },
          { name: "submittedAt", type: "uint64" },
          { name: "challengeDeadline", type: "uint64" },
          { name: "matchedMarketCap", type: "uint256" },
          { name: "retainedCostTotal", type: "uint256" },
          { name: "refundTotal", type: "uint256" },
          { name: "completeSetCount", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "getPostgradAdapter",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "hasClearingRoot",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "marketId", type: "uint256" }],
    name: "startGraduation",
    outputs: [{ name: "snapshotHash", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { name: "marketId", type: "uint256" },
          { name: "merkleRoot", type: "bytes32" },
          { name: "matchedMarketCap", type: "uint256" },
          { name: "retainedCostTotal", type: "uint256" },
          { name: "refundTotal", type: "uint256" },
          { name: "completeSetCount", type: "uint256" },
        ],
        name: "params",
        type: "tuple",
      },
    ],
    name: "submitClearingRoot",
    outputs: [{ name: "snapshotHash", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "metadataHash", type: "bytes32" },
      { indexed: false, name: "metadataURI", type: "string" },
      { indexed: false, name: "collateral", type: "address" },
      { indexed: false, name: "openingProbabilityWad", type: "uint256" },
      { indexed: false, name: "liquidityParameter", type: "uint256" },
      { indexed: false, name: "graduationThreshold", type: "uint256" },
      { indexed: false, name: "graduationDeadline", type: "uint64" },
      { indexed: false, name: "resolutionTime", type: "uint64" },
      { indexed: false, name: "bypassAiResolution", type: "bool" },
    ],
    name: "MarketCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "MarketCreationFeePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "receiptId", type: "uint256" },
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "shares", type: "uint256" },
      { indexed: false, name: "cost", type: "uint256" },
      { indexed: false, name: "rLow", type: "int256" },
      { indexed: false, name: "rHigh", type: "int256" },
      { indexed: false, name: "sequence", type: "uint64" },
    ],
    name: "ReceiptPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "manager", type: "address" },
      { indexed: false, name: "receiptCount", type: "uint256" },
      { indexed: false, name: "totalEscrowed", type: "uint256" },
      { indexed: false, name: "path", type: "int256" },
      { indexed: false, name: "yesShares", type: "uint256" },
      { indexed: false, name: "noShares", type: "uint256" },
      { indexed: false, name: "graduationStartedAt", type: "uint64" },
      { indexed: false, name: "snapshotHash", type: "bytes32" },
    ],
    name: "GraduationStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "submitter", type: "address" },
      { indexed: true, name: "merkleRoot", type: "bytes32" },
      { indexed: false, name: "snapshotHash", type: "bytes32" },
      { indexed: false, name: "matchedMarketCap", type: "uint256" },
      { indexed: false, name: "retainedCostTotal", type: "uint256" },
      { indexed: false, name: "refundTotal", type: "uint256" },
      { indexed: false, name: "completeSetCount", type: "uint256" },
      { indexed: false, name: "submittedAt", type: "uint64" },
      { indexed: false, name: "challengeDeadline", type: "uint64" },
    ],
    name: "ClearingRootSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: false, name: "totalEscrowed", type: "uint256" },
    ],
    name: "MarketRefundsAvailable",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "postgradAdapter", type: "address" },
      { indexed: true, name: "postgradMarket", type: "address" },
      { indexed: false, name: "completeSetCount", type: "uint256" },
      { indexed: false, name: "retainedCostTotal", type: "uint256" },
      { indexed: false, name: "refundTotal", type: "uint256" },
    ],
    name: "GraduationFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "receiptId", type: "uint256" },
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "retainedShares", type: "uint256" },
      { indexed: false, name: "retainedCost", type: "uint256" },
      { indexed: false, name: "refund", type: "uint256" },
    ],
    name: "GraduatedReceiptClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "receiptId", type: "uint256" },
      { indexed: true, name: "marketId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "refund", type: "uint256" },
    ],
    name: "RefundedReceiptClaimed",
    type: "event",
  },
] as const;
