// The review-bond vault ABI comes straight from the protocol workspace package
// (protocol/src/generated/review-bond-vault.ts, regenerated by `protocol
// build`). This re-export keeps ABIs quarantined under integrations/contracts:
// app code imports from here, never from @popcharts/protocol directly. The
// subpath export maps straight to the generated module (see the pregrad
// manager shim for the Turbopack rationale).
export { reviewBondVaultAbi } from "@popcharts/protocol/review-bond-vault";
