import { writeFileSync } from "node:fs";

import { type PregradDeploy } from "../deployments/pregradDeploy.ts";
import { type PostgradDeployment } from "../deployments/readPostgradDeployment.ts";
import { postgradServerEnvLines } from "./postgradEnv.ts";

/**
 * Writes the generated local-chain server env file that downstream tools ride
 * (the AI runners wait on it before signing, bot-trade and the lifecycle
 * runner load it standalone). Shared by the local-dev and lifecycle-nightly
 * orchestrators so the key set cannot drift between them; local-chain-smoke
 * keeps its own smaller writer (no AI services in that stack).
 */
export function writeLocalChainServerEnv({
  deploy,
  env,
  envFilePath,
  generatedBy,
  postgrad,
}: {
  deploy: PregradDeploy;
  env: NodeJS.ProcessEnv;
  envFilePath: string;
  /** Script path recorded in the file header, e.g. "scripts/local-dev.ts". */
  generatedBy: string;
  postgrad: PostgradDeployment | null;
}): void {
  const lines = [
    `# Generated by ${generatedBy}.`,
    "# Safe to delete; ignored by git.",
    `DATABASE_URL=${env.DATABASE_URL}`,
    `PORT=${env.PORT}`,
    "NETWORK=local",
    `POPCHARTS_ADMIN_REVIEW_ENABLED=${env.POPCHARTS_ADMIN_REVIEW_ENABLED}`,
    `POPCHARTS_DEV_TOOLS_ENABLED=${env.POPCHARTS_DEV_TOOLS_ENABLED}`,
    `AI_REVIEW_SERVICE_URL=${env.AI_REVIEW_SERVICE_URL}`,
    `AI_REVIEW_RUNNER_POLL_MS=${env.AI_REVIEW_RUNNER_POLL_MS}`,
    `RPC_HTTP_URL=${env.RPC_HTTP_URL}`,
    `RPC_WSS_URL=${env.RPC_WSS_URL}`,
    `PREGRAD_MANAGER_ADDRESS=${deploy.pregradManagerAddress}`,
    `PREGRAD_MANAGER_DEPLOY_BLOCK=${deploy.deployBlock}`,
    `LOCAL_PREGRAD_MANAGER_ADDRESS=${deploy.pregradManagerAddress}`,
    `LOCAL_PREGRAD_MANAGER_DEPLOY_BLOCK=${deploy.deployBlock}`,
    `LOCAL_COLLATERAL_ADDRESS=${deploy.collateralAddress}`,
    `LOCAL_POSTGRAD_ADAPTER_ADDRESS=${deploy.postgradAdapterAddress}`,
    ...postgradServerEnvLines(postgrad),
    `HEALTH_CHECK_FILE=${env.HEALTH_CHECK_FILE}`,
    "",
  ];

  writeFileSync(envFilePath, lines.join("\n"));
}
