import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { parseEnvFile } from "../shared/env/parseEnvFile.ts";

describe("parseEnvFile", () => {
  it("parses KEY=VALUE lines, skipping comments and blanks", () => {
    const parsed = parseEnvFile(
      [
        "# Generated by scripts/local-chain-smoke.ts.",
        "",
        "DATABASE_URL=postgresql://postgres:postgres@localhost:5433/popcharts",
        "PREGRAD_MANAGER_ADDRESS=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
        "EMPTY=",
        "URL_WITH_EQUALS=postgresql://u:p@h/db?a=1&b=2",
      ].join("\n"),
    );

    assert.deepEqual(parsed, {
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/popcharts",
      PREGRAD_MANAGER_ADDRESS: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      EMPTY: "",
      URL_WITH_EQUALS: "postgresql://u:p@h/db?a=1&b=2",
    });
  });

  it("ignores malformed lines without a key", () => {
    assert.deepEqual(parseEnvFile("=nokey\njust-noise\n"), {});
  });
});
