import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import { readEnvFile } from "../shared/env/readEnvFile.ts";

/** Writes `contents` to a throwaway env file and returns its path. */
function writeEnvFile(contents: string): string {
  const file = join(mkdtempSync(join(tmpdir(), "popcharts-env-")), ".env.test");
  writeFileSync(file, contents);

  return file;
}

describe("readEnvFile", () => {
  it("parses KEY=VALUE lines, skipping comments and blanks", () => {
    const parsed = readEnvFile(
      writeEnvFile(
        [
          "# Generated by scripts/local-chain-smoke.ts.",
          "",
          "DATABASE_URL=postgresql://postgres:postgres@localhost:5433/popcharts",
          "PREGRAD_MANAGER_ADDRESS=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
          "EMPTY=",
          "URL_WITH_EQUALS=postgresql://u:p@h/db?a=1&b=2",
        ].join("\n"),
      ),
    );

    assert.deepEqual(parsed, {
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/popcharts",
      PREGRAD_MANAGER_ADDRESS: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      EMPTY: "",
      URL_WITH_EQUALS: "postgresql://u:p@h/db?a=1&b=2",
    });
  });

  it("ignores malformed lines without a key", () => {
    assert.deepEqual(readEnvFile(writeEnvFile("=nokey\njust-noise\n")), {});
  });

  it("lets a later key win and keeps `=` inside values", () => {
    const parsed = readEnvFile(
      writeEnvFile(
        [
          "PREGRAD_MANAGER_ADDRESS=0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
          "EQUALS_IN_VALUE=a=b",
          "PREGRAD_MANAGER_ADDRESS=0x1111111111111111111111111111111111111111",
        ].join("\n"),
      ),
    );

    assert.deepEqual(parsed, {
      PREGRAD_MANAGER_ADDRESS: "0x1111111111111111111111111111111111111111",
      EQUALS_IN_VALUE: "a=b",
    });
  });

  it("accepts CRLF line endings", () => {
    const parsed = readEnvFile(
      writeEnvFile("RPC_HTTP_URL=http://127.0.0.1:8545\r\nPORT=3001\r\n"),
    );

    assert.deepEqual(parsed, {
      RPC_HTTP_URL: "http://127.0.0.1:8545",
      PORT: "3001",
    });
  });
});
