import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import { type PregradDeploy } from "../shared/deployments/pregradDeploy.ts";
import { type PostgradDeployment } from "../shared/deployments/readPostgradDeployment.ts";
import { writeLocalChainServerEnv } from "../shared/env/writeLocalChainServerEnv.ts";

function tempEnvFile(): string {
  return join(
    mkdtempSync(join(tmpdir(), "popcharts-local-chain-env-")),
    ".env.local-chain",
  );
}

// Non-address fixture values are deliberately obvious so the pinned output
// below reads as a spec for the key set, not a set of magic strings.
const DEPLOY: PregradDeploy = {
  chainId: 31337,
  collateralAddress: "0x0000000000000000000000000000000000000c01",
  deployBlock: "42",
  postgradAdapterAddress: "0x0000000000000000000000000000000000000ada",
  pregradManagerAddress: "0x0000000000000000000000000000000000000b01",
};

const ENV: NodeJS.ProcessEnv = {
  DATABASE_URL: "postgres://db",
  PORT: "3001",
  POPCHARTS_ADMIN_REVIEW_ENABLED: "true",
  POPCHARTS_DEV_TOOLS_ENABLED: "true",
  AI_REVIEW_SERVICE_URL: "http://127.0.0.1:4001",
  AI_REVIEW_RUNNER_POLL_MS: "1000",
  RPC_HTTP_URL: "http://127.0.0.1:8545",
  RPC_WSS_URL: "ws://127.0.0.1:8545",
  HEALTH_CHECK_FILE: "/tmp/health",
};

describe("writeLocalChainServerEnv", function () {
  // This file is the single source of truth for the generated key set (the
  // control plane, local-dev, and lifecycle-nightly all route through it). If
  // this pinned output changes, confirm every consumer of the env file expects
  // the new keys before updating the expectation — silent drift is the bug the
  // shared helper exists to prevent.
  it("renders the full key set with no postgrad venue", function () {
    const envFilePath = tempEnvFile();

    writeLocalChainServerEnv({
      deploy: DEPLOY,
      env: ENV,
      envFilePath,
      generatedBy: "scripts/local-dev-control.ts",
      postgrad: null,
    });

    assert.equal(
      readFileSync(envFilePath, "utf8"),
      [
        "# Generated by scripts/local-dev-control.ts.",
        "# Safe to delete; ignored by git.",
        "DATABASE_URL=postgres://db",
        "PORT=3001",
        "NETWORK=local",
        "POPCHARTS_ADMIN_REVIEW_ENABLED=true",
        "POPCHARTS_DEV_TOOLS_ENABLED=true",
        "AI_REVIEW_SERVICE_URL=http://127.0.0.1:4001",
        "AI_REVIEW_RUNNER_POLL_MS=1000",
        "RPC_HTTP_URL=http://127.0.0.1:8545",
        "RPC_WSS_URL=ws://127.0.0.1:8545",
        "PREGRAD_MANAGER_ADDRESS=0x0000000000000000000000000000000000000b01",
        "PREGRAD_MANAGER_DEPLOY_BLOCK=42",
        "LOCAL_PREGRAD_MANAGER_ADDRESS=0x0000000000000000000000000000000000000b01",
        "LOCAL_PREGRAD_MANAGER_DEPLOY_BLOCK=42",
        "LOCAL_COLLATERAL_ADDRESS=0x0000000000000000000000000000000000000c01",
        "LOCAL_POSTGRAD_ADAPTER_ADDRESS=0x0000000000000000000000000000000000000ada",
        "HEALTH_CHECK_FILE=/tmp/health",
        "",
      ].join("\n"),
    );
  });

  it("records the calling orchestrator in the header", function () {
    const envFilePath = tempEnvFile();

    writeLocalChainServerEnv({
      deploy: DEPLOY,
      env: ENV,
      envFilePath,
      generatedBy: "scripts/local-lifecycle-nightly.ts",
      postgrad: null,
    });

    assert.match(
      readFileSync(envFilePath, "utf8"),
      /^# Generated by scripts\/local-lifecycle-nightly\.ts\.\n/,
    );
  });

  it("injects the venue lines ahead of HEALTH_CHECK_FILE when a venue is deployed", function () {
    const envFilePath = tempEnvFile();
    const postgrad: PostgradDeployment = {
      boundedHook: "0x00000000000000000000000000000000000000a1",
      marketAddress: "0x00000000000000000000000000000000000000a2",
      marketSymbol: "DEMO",
      noPoolId: "0x00000000000000000000000000000000000000b1",
      noTokenAddress: "0x00000000000000000000000000000000000000a3",
      orderManager: "0x00000000000000000000000000000000000000a4",
      poolManager: "0x00000000000000000000000000000000000000a5",
      poolTickBounds: "0x00000000000000000000000000000000000000a6",
      postgradAdapter: "0x0000000000000000000000000000000000000ada",
      quoter: "0x00000000000000000000000000000000000000a7",
      stateView: "0x00000000000000000000000000000000000000a8",
      swapRouter: "0x00000000000000000000000000000000000000a9",
      yesPoolId: "0x00000000000000000000000000000000000000b2",
      yesTokenAddress: "0x00000000000000000000000000000000000000aa",
    };

    writeLocalChainServerEnv({
      deploy: DEPLOY,
      env: ENV,
      envFilePath,
      generatedBy: "scripts/local-dev.ts",
      postgrad,
    });

    const lines = readFileSync(envFilePath, "utf8").split("\n");
    const venueIndex = lines.indexOf("COMPLETE_SET_MARKET_SYMBOL=DEMO");
    const healthIndex = lines.indexOf("HEALTH_CHECK_FILE=/tmp/health");
    assert.notEqual(venueIndex, -1);
    assert.notEqual(healthIndex, -1);
    assert.ok(venueIndex < healthIndex);
  });
});
