// Generates src/integrations/contracts/pregrad-manager.ts from the protocol
// workspace's committed contract metadata, mirroring how orval consumes
// server/generated/openapi.json. Run via `pnpm run abi:generate`; `--check`
// fails without writing when the committed file is stale.
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(scriptDir, "..");
const sourcePath = resolve(appRoot, "../protocol/src/generated/pregrad-manager.ts");
const outputPath = resolve(appRoot, "src/integrations/contracts/pregrad-manager.ts");

const checkOnly = process.argv.includes("--check");

async function main(): Promise<void> {
  const source = (await import(pathToFileURL(sourcePath).href)) as {
    pregradManagerAbi?: readonly unknown[];
  };
  const abi = source.pregradManagerAbi;

  if (!Array.isArray(abi) || abi.length === 0) {
    throw new Error(`Expected a non-empty pregradManagerAbi export in ${sourcePath}`);
  }

  const rendered = `// This file is generated by scripts/generate-contract-abis.mts from
// protocol/src/generated/pregrad-manager.ts. Do not edit it directly; rebuild
// the protocol workspace and run \`pnpm run abi:generate\` here instead.

import type { Abi } from "viem";

export const pregradManagerAbi = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;
`;
  const content = await formatTypeScript(rendered, outputPath);

  if (checkOnly) {
    const current = existsSync(outputPath) ? await readFile(outputPath, "utf8") : "";

    if (current !== content) {
      console.error(
        `Generated contract ABI at ${outputPath} is out of date. ` +
          "Run `pnpm run abi:generate`."
      );
      process.exitCode = 1;
    }

    return;
  }

  await writeFile(outputPath, content);
}

async function formatTypeScript(source: string, filepath: string): Promise<string> {
  const prettier = await import("prettier");
  const config = (await prettier.resolveConfig(filepath)) ?? {};

  return prettier.format(source, { ...config, filepath });
}

await main();
